### ISSUE TITLE
Regenerate by WP CLI ERROR 

### ISSUE THREAD

**Issue by franklysaputra** [ddur/Warp-iMagick#5]
Hi there,

Tried to regenerate media by WP CLI but not working. Here's the error message

`Found 57 images to regenerate.
Lib::error: Regenerate wp_create_image_subsizes( _, $attachment_id ) argument mismatch!
Lib::error: Wrong editor class selected: WP_Image_Editor_GD
PHP Fatal error:  Uncaught Error: Class 'ddur\Warp_iMagick\WP_Error' not found in /home/runcloud/webapps/test/wp-content/plugins/warp-imagick/classes/class-shared.php:486
Stack trace:
#0 /home/runcloud/webapps/test/wp-content/plugins/warp-imagick/classes/class-plugin.php(1227): ddur\Warp_iMagick\Shared::get_warp_editor()
#1 /home/runcloud/webapps/test/wp-includes/class-wp-hook.php(308): ddur\Warp_iMagick\Plugin->on_intermediate_image_sizes_advanced_99_filter()
#2 /home/runcloud/webapps/test/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /home/runcloud/webapps/test/wp-admin/includes/image.php(375): apply_filters()
#4 /home/runcloud/webapps/test/wp-admin/includes/image.php(496): wp_create_image_subsizes()
#5 phar:///RunCloud/Packages/RunCloudAgent/bin/wp-cli/vendor/wp-cli/media-command/src/Media_Command.php(592): wp_generate_attachment_metadata()
#6 phar:///RunCloud/Packages/RunCloudAgent/bin/wp-cli/vendor/wp-cli/media-command/src/Media_Command.php(162): Media_Command->pr in /home/runcloud/webapps/test/wp-content/plugins/warp-imagick/classes/class-shared.php on line 486
Fatal error: Uncaught Error: Class 'ddur\Warp_iMagick\WP_Error' not found in /home/runcloud/webapps/test/wp-content/plugins/warp-imagick/classes/class-shared.php:486
Stack trace:
#0 /home/runcloud/webapps/test/wp-content/plugins/warp-imagick/classes/class-plugin.php(1227): ddur\Warp_iMagick\Shared::get_warp_editor()
#1 /home/runcloud/webapps/test/wp-includes/class-wp-hook.php(308): ddur\Warp_iMagick\Plugin->on_intermediate_image_sizes_advanced_99_filter()
#2 /home/runcloud/webapps/test/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /home/runcloud/webapps/test/wp-admin/includes/image.php(375): apply_filters()
#4 /home/runcloud/webapps/test/wp-admin/includes/image.php(496): wp_create_image_subsizes()
#5 phar:///RunCloud/Packages/RunCloudAgent/bin/wp-cli/vendor/wp-cli/media-command/src/Media_Command.php(592): wp_generate_attachment_metadata()
#6 phar:///RunCloud/Packages/RunCloudAgent/bin/wp-cli/vendor/wp-cli/media-command/src/Media_Command.php(162): Media_Command->pr in /home/runcloud/webapps/test/wp-content/plugins/warp-imagick/classes/class-shared.php on line 486
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.`

It's working fine with regenerate thumbnails plugin.

Thanks!

**Comment by splaquet** [comment]
Which version of PHP are you using?

I might be mistaken, but I believe that you have an incompatible Library mod enabled, **WP_Image_Editor_GD**

`Lib::error: Wrong editor class selected: WP_Image_Editor_GD `

**Comment by ddur** [comment]
@franklysaputra 

I can't reproduce this issue. Please use regenerate thumbnails plugin until issue is resolved.

**Comment by ddur** [comment]
@franklysaputra 

To prevent fatal error, You may replace line 
https://github.com/ddur/Warp-iMagick/blob/main/warp-imagick/classes/class-shared.php#L486
with 
```php
				return new \WP_Error( 'warp-imagick', $msg );
```


But there still may be issue with wrongly selected editor.
`Lib::error: Wrong editor class selected: WP_Image_Editor_GD `

Try to deactivate and activate warp-imagick to possibly override conflict with another incompatible plugin that is messing with WordPress image editors.

Known conflict plugins You should not use along with warp-imagick:
```php
			$known_conflict_slugs = array(
				'wp-email-users',
				'ajax-search-lite',
				'circles-gallery',
'''

**Comment by ddur** [comment]
@splaquet 

Thank you for your help and effort to debug an issue

**Comment by ddur** [comment]
@franklysaputra 

Check/follow this issue https://github.com/ddur/Warp-iMagick/issues/8
